# Generated by Django 5.1.7 on 2025-05-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.TextField(default='static/img/noimg.jpg', verbose_name='ImgPath'),
        ),
    ]
