# Generated by Django 5.1.7 on 2025-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
