# Generated by Django 5.1.7 on 2025-05-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
